grocery/note/urls.py
from django.conf.urls import url
from grocery.note.views import (note_detail, new_note)

urlpatterns = [
    url(r'^new/$', new_note, name='new_note'),
    url(r'^(?P<note_id>\d+)/$', note_detail,
        name='note_detail'),
]

grocery/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from grocery.note.views import user_login, user_logout
from grocery.properties.views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^note/', include('grocery.note.urls')),
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),

    url(r'^user/', include('grocery.accounts.urls')),
    url(r'^categroy/', include('grocery.properties.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

grocery/note/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Tags(models.Model):
    name = models.CharField(max_length=16, verbose_name=u'标签名称')
    is_self = models.BooleanField(default=False, verbose_name=u'自定义标签')

    class Mate:
        default_relate_name = u'类型'

    def __unicode__(self):
        return self.name


class Content(models.Model):
    author = models.ForeignKey(User, verbose_name=u'作者')
    tags = models.ManyToManyField(Tags, verbose_name=u'标签')
    title = models.CharField(max_length=72, verbose_name=u'标题',
                             db_index=True)
    context = models.TextField(verbose_name=u'内容')
    keywords = models.CharField(max_length=36, verbose_name=u'关键词',
                                db_index=True, blank=True, null=True)
    desc = models.TextField(verbose_name=u'简介', blank=True, null=True)
    create_time = models.DateTimeField(auto_now_add=True,
                                       verbose_name=u'创建时间')
    update_time = models.DateTimeField(auto_now=True,
                                       verbose_name=u'更新时间')
    click_rate = models.IntegerField(default=0, verbose_name='点击量')

    class Mate:
        ordering = ('-update_time', )
        verbose_name = verbose_name_plural = u'笔记／文章'

    def __unicode__(self):
        return self.title

grocery/note/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from grocery.note.models import Content


class LoginForm(forms.Form):
    username = forms.CharField(label=u'用户名',
                               error_messages={'required': u'请输入用户名'})
    password = forms.CharField(label=u'密码',
                               error_messages={'required': u'请输入密码'},
                               widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'

    def clean_username(self):
        username = self.cleaned_data.get('username', '')
        if not User.objects.filter(username=username).exists():
                self._errors['username'] = self.error_class(['用户不存在'])
        return username

    def clean(self):
        super(LoginForm, self).clean()
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user:
            self._errors['password'] = self.error_class([u'密码错误，请重新填写'])
        self.cleaned_data['user'] = user
        return self.cleaned_data


class NoteForm(forms.ModelForm):

    class Meta:
        model = Content
        exclude = ('create_time', 'update_time', 'click_rate', 'author',
                   'desc', 'tags', )

    def clean_title(self):
        title = self.cleaned_data.get('title', '')
        if not title:
            self._errors['title'] = self.error_class([u'请取个标题'])
        if len(title) > 72:
            self._errors['title'] = self.error_class([u'请使用小与72个字的标题'])
        return title

    def clean_context(self):
        context = self.cleaned_data.get('context', '')
        if not context:
            self._errors['context'] = self.error_class([u'请输入文章内容'])
        return context

    def clean(self):
        super(NoteForm, self).clean()
        return self.cleaned_data

grocery/note/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404
from grocery.note.models import Content, Tags
from grocery.note.forms import LoginForm, NoteForm


def home(request):
    notes = Content.objects.all()
    return render(request, 'note/home.html', {'notes': notes})


def user_login(request):
    next_url = request.GET.get('next', '')
    login_form = LoginForm()
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            login(request, user)
            if next_url:
                return redirect(next_url)
            return redirect('home')
    ctx = {
        'login_form': login_form,
        'next_url': next_url,
    }
    return render(request, 'login.html', ctx)


def user_logout(request):
    pass


@login_required
def new_note(request):
    form = NoteForm()
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            user = request.user
            note.author = user
            note.save()
            return redirect(reverse('note_detail', args=(note.id, )))
    ctx = {'form': form}
    return render(request, 'note/new.html', ctx)


def note_detail(request, note_id):
    note = get_object_or_404(Content, pk=note_id)
    ctx = {'note': note}
    return render(request, 'note/note_detail.html', ctx)

templates/note/home.html
{% extends 'base.html' %}

{% block content %}
  {% for note in notes %}
    <article id="{{ note.id }}" class="article-list">
      <div class="article-head">
        <h1 class="article-title">
          {{ note.title }}
        </h1>
        <div class="article-meta">
          <span class="author">
            作者：
            <a href="#">{{ note.author.username }}</a>
          </span>
          ·
          <span class="article-date">{{ note.create_time|date:'Y年m月d日' }}</span>
        </div>
      </div>
      <div class="article-content">
        <p>
          {{ note.context|safe }}
        </p>
      </div>
      <div class="article-detaillink">
        <a href="{% url 'note_detail' note.id %}" class="btn btn-default">查看全文</a>
      </div>
      <footer class="article-footer clearfix">
        <div class="pull-left tag-list">
          <i class="glyphicon glyphicon-tags"></i>
          <a href="#">Python</a>，
          <a href="#">Javascript</a>
        </div>
      </footer>
    </article>
  {% endfor %}
{% endblock %}

templates/note/new.html
{% extends 'base.html' %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'libs/editormd/css/editormd.min.css' %}">
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'libs/editormd/js/editormd.min.js' %}"></script>
<script>

</script>
{% endblock %}

{% block container %}
<div class="container-fluid">
<form class="form-horizontal article-list" action="{% url 'new_note' %}" method="POST"> {% csrf_token %}
  <div class="form-group">
    <label for="id_title" class="col-sm-2 control-label">
      {{ form.title.label }}
    </label>
    <div class="col-sm-10">
      {{ form.title }}
    </div>
  </div>
  <div class="article-content">
    <div class="form-group">
      <label for="id_context" class="col-sm-2 control-label">
        {{ form.context.label }}
      </label>
    </div>
    <div class="form-group">
      <div class="col-sm-2"></div>
      <div class="col-sm-10">
        {{ form.context }}
      </div>
    </div>
  </div>
  <div class="article-detaillink">
    <button type="submit" class="btn btn-default">保存</button>
  </div>
</form>
</div>
{% endblock %}

templates/note/note_detail.html
{% extends 'base.html' %}

{% block content %}
<article id="001" class="article-list">
  <div class="article-head">
    <h1 class="article-title">
      {{ note.title }}
    </h1>
    <div class="article-meta">
      <span class="author">
        作者：
        <a href="#">{{ note.author.username }}</a>
      </span>
      ·
      <span class="article-date">{{ note.create_time|date:'Y年m月d日' }}</span>
    </div>
  </div>
  <div class="article-content">
    <p>
      {{ note.context }}
    </p>
  </div>
  <footer class="article-footer clearfix">
    <div class="pull-left tag-list">
      <i class="glyphicon glyphicon-tags"></i>
      <a href="#">Python</a>，
      <a href="#">Javascript</a>
      {% filter force_escape|upper %}
        This text will be HTML-escaped, and will appear in all lowercase.
      {% endfilter %}
    </div>
  </footer>
</article>
{% endblock %}